// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct Album {
  var name: String
  var thumbnail: String
  var photoCount: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Album? {
    let name = pigeonVar_list[0] as! String
    let thumbnail = pigeonVar_list[1] as! String
    let photoCount = pigeonVar_list[2] as! Int64

    return Album(
      name: name,
      thumbnail: thumbnail,
      photoCount: photoCount
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      thumbnail,
      photoCount,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct Photo {
  var path: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Photo? {
    let path = pigeonVar_list[0] as! String

    return Photo(
      path: path
    )
  }
  func toList() -> [Any?] {
    return [
      path
    ]
  }
}

private class PhotoGalleryApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return Album.fromList(self.readValue() as! [Any?])
    case 130:
      return Photo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PhotoGalleryApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Album {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? Photo {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PhotoGalleryApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PhotoGalleryApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PhotoGalleryApiPigeonCodecWriter(data: data)
  }
}

class PhotoGalleryApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PhotoGalleryApiPigeonCodec(readerWriter: PhotoGalleryApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PhotoGalleryNativeHostApi {
  func getAlbums() throws -> [Album]
  func getPhotos(album: String) throws -> [Photo]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PhotoGalleryNativeHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PhotoGalleryApiPigeonCodec.shared }
  /// Sets up an instance of `PhotoGalleryNativeHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PhotoGalleryNativeHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getAlbumsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.photo_gallery.PhotoGalleryNativeHostApi.getAlbums\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAlbumsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAlbums()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAlbumsChannel.setMessageHandler(nil)
    }
    let getPhotosChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.photo_gallery.PhotoGalleryNativeHostApi.getPhotos\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPhotosChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let albumArg = args[0] as! String
        do {
          let result = try api.getPhotos(album: albumArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPhotosChannel.setMessageHandler(nil)
    }
  }
}
