// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class Album (
  val name: String,
  val thumbnail: String,
  val photoCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Album {
      val name = pigeonVar_list[0] as String
      val thumbnail = pigeonVar_list[1] as String
      val photoCount = pigeonVar_list[2] as Long
      return Album(name, thumbnail, photoCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      thumbnail,
      photoCount,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Photo (
  val path: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Photo {
      val path = pigeonVar_list[0] as String
      return Photo(path)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
    )
  }
}
private open class PhotoGalleryApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Album.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Photo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is Album -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is Photo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PhotoGalleryNativeHostApi {
  fun getAlbums(): List<Album>
  fun getPhotos(album: String): List<Photo>

  companion object {
    /** The codec used by PhotoGalleryNativeHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PhotoGalleryApiPigeonCodec()
    }
    /** Sets up an instance of `PhotoGalleryNativeHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PhotoGalleryNativeHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.photo_gallery.PhotoGalleryNativeHostApi.getAlbums$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAlbums())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.photo_gallery.PhotoGalleryNativeHostApi.getPhotos$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val albumArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getPhotos(albumArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
